# Generated by Django 5.2.5 on 2025-09-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('sujet', 'Sujet'), ('correction', 'Correction'), ('tuto', 'Tutoriel'), ('livre', 'Livre')], max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Utilisateur.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='Ressource.ressource')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='Utilisateur.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Utilisateur.utilisateur')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Ressource.ressource')),
            ],
            options={
                'unique_together': {('utilisateur', 'ressource')},
            },
        ),
    ]
