# Generated by Django 5.2.5 on 2025-09-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ressource', '0002_alter_favori_utilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telechargement',
            old_name='utilisateur',
            new_name='proprietaire',
        ),
    ]
